// D3: the scheduled run's entry point.
//
// ─────────────────────────────────────────────────────────────────────
// THE CRON DECISION, and why it went this way
// ─────────────────────────────────────────────────────────────────────
// A Cloudflare Cron Trigger does NOT send an HTTP request. It invokes the
// Worker's exported `scheduled(event, env, ctx)` handler. So a cron
// trigger can only work if the deployed Worker exports `scheduled`.
//
// This project's Worker entry is GENERATED by @astrojs/cloudflare v14, not
// written by us. That generated entry is
// node_modules/@astrojs/cloudflare/dist/entrypoints/server.js, and it is
// four lines long:
//
//     import { handle } from "../utils/handler.js";
//     var server_default = { fetch: handle };
//     export { server_default as default };
//
// It exports `fetch` and nothing else. The adapter exposes no option,
// hook, or documented mechanism for contributing a `scheduled` export
// (verified by searching the installed adapter for "scheduled": no
// matches anywhere in dist/). Adding one would mean replacing the
// generated entry with a hand written wrapper and pointing `main` at it,
// which means owning a file the adapter expects to own and re-checking it
// on every adapter upgrade. That is a fragile trade for a nightly job.
//
// DECISION: do not fight the adapter. Expose the job as an HTTP endpoint
// guarded by a shared secret, and drive it from any scheduler that can
// make an HTTPS request. The cron trigger config is written into
// wrangler.jsonc but left COMMENTED OUT, with the same explanation, so
// nobody enables it and then wonders why nothing fires.
//
// HOW TO ACTUALLY DRIVE IT (pick one):
//   1. Any external scheduler that can POST: GitHub Actions on a schedule,
//      cron-job.org, Zapier, or a cron line on any machine:
//        curl -X POST https://<site>/api/ai-cron \
//             -H "authorization: Bearer $CRON_SECRET"
//   2. A tiny separate Cloudflare Worker whose only job is a `scheduled`
//      handler that fetches the URL above. That is the option that keeps
//      everything inside Cloudflare, and it stays a handful of lines.
//
// Set the secret first:  npx wrangler secret put CRON_SECRET
//
// ─────────────────────────────────────────────────────────────────────
// AUTHENTICATION
// ─────────────────────────────────────────────────────────────────────
// No session and no CSRF, because there is no browser and no user here.
// A bearer secret compared in CONSTANT TIME instead: a plain === on a
// secret leaks its length and its matching prefix through timing, and this
// endpoint is publicly reachable, so that matters.
//
// The path deliberately sits outside /api/admin so middleware.ts does not
// try to resolve a session for it and reject it before it starts.
export const prerender = false;

import type { APIRoute } from 'astro';
import { getAiStores } from '../../lib/ai/context.ts';
import { runScheduledJob } from '../../lib/ai/autopublish.ts';

/** Length-safe, timing-safe string comparison. */
function secretsMatch(a: string, b: string): boolean {
  const ab = new TextEncoder().encode(a);
  const bb = new TextEncoder().encode(b);
  // Compare a fixed number of bytes regardless of input length, and fold
  // the length difference into the result so a short guess cannot pass.
  let diff = ab.length ^ bb.length;
  const len = Math.max(ab.length, bb.length);
  for (let i = 0; i < len; i++) {
    diff |= (ab[i] ?? 0) ^ (bb[i] ?? 0);
  }
  return diff === 0;
}

function unauthorized(): Response {
  return new Response(JSON.stringify({ error: 'unauthorized' }), {
    status: 401,
    headers: { 'content-type': 'application/json' },
  });
}

export const POST: APIRoute = async ({ request, locals, url }) => {
  const { env } = await import('cloudflare:workers');
  const secret = (env as any)?.CRON_SECRET as string | undefined;

  // A missing secret means the job is NOT configured, and an unconfigured
  // scheduled job must never run for anyone. Failing closed is the only
  // safe reading of "the secret is not set".
  if (!secret) {
    return new Response(
      JSON.stringify({ error: 'CRON_SECRET is not configured; the scheduled job is disabled' }),
      { status: 503, headers: { 'content-type': 'application/json' } }
    );
  }

  const header = request.headers.get('authorization') ?? '';
  const presented = header.startsWith('Bearer ') ? header.slice(7) : '';
  if (!presented || !secretsMatch(presented, secret)) return unauthorized();

  const aiStores = getAiStores();
  const { articles } = locals.stores!;

  const report = await runScheduledJob({
    aiStores,
    articles,
    resendApiKey: (env as any)?.RESEND_API_KEY as string | undefined,
    siteOrigin: url.origin,
  });

  return new Response(JSON.stringify(report, null, 2), {
    status: 200,
    headers: { 'content-type': 'application/json', 'cache-control': 'no-store' },
  });
};
