// Generates the D1 seed SQL: the first admin plus the existing articles.
//
// It does NOT print the password to stdout. The password is written to
// `data/ADMIN_PASSWORD.txt`, which is gitignored. Read it, store it in a
// password manager, then delete the file.
//
// Usage:
//   node scripts/cms-seed.mjs                 -> writes migrations/0003_seed.sql
//   ADMIN_PASSWORD=... node scripts/cms-seed.mjs   -> use your own password
//
// Then apply it:
//   npx wrangler d1 execute lahav-cms --local  --file=./migrations/0001_init.sql
//   npx wrangler d1 execute lahav-cms --local  --file=./migrations/0003_seed.sql
//   (swap --local for --remote when the real database exists)
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { webcrypto as crypto } from 'node:crypto';

const ROOT = process.cwd();
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'itsu60ai@gmail.com';
const ADMIN_NAME = process.env.ADMIN_NAME || 'איתן להב';

// ── the same PBKDF2 parameters the Worker uses, so hashes verify ────
const ITERATIONS = 100_000;
const enc = new TextEncoder();
const hex = (buf) => [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, '0')).join('');

async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const key = await crypto.subtle.importKey('raw', enc.encode(password), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' }, key, 256
  );
  return { hash: hex(bits), salt: hex(salt.buffer) };
}

function strongPassword() {
  // ~98 bits of entropy. High entropy is what carries the security here,
  // because Cloudflare caps PBKDF2 iterations well below OWASP guidance.
  const alpha = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const bytes = crypto.getRandomValues(new Uint8Array(24));
  let out = '';
  for (let i = 0; i < 24; i++) {
    if (i > 0 && i % 6 === 0) out += '-';
    out += alpha[bytes[i] % alpha.length];
  }
  return out;
}

const q = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);

const generated = !process.env.ADMIN_PASSWORD;
const password = process.env.ADMIN_PASSWORD || strongPassword();
const { hash, salt } = await hashPassword(password);
const userId = hex(crypto.getRandomValues(new Uint8Array(16)).buffer);
const now = new Date().toISOString();

const lines = [
  '-- Generated by scripts/cms-seed.mjs. Contains a password HASH, never a password.',
  '-- Safe to commit only if you accept publishing the admin email. Prefer not to.',
  '',
  'DELETE FROM sessions;',
  'DELETE FROM users;',
  '',
  `INSERT INTO users (id, email, name, role, password_hash, password_salt, failed_count, locked_until, created_at)`,
  `VALUES (${q(userId)}, ${q(ADMIN_EMAIL)}, ${q(ADMIN_NAME)}, 'admin', ${q(hash)}, ${q(salt)}, 0, NULL, ${q(now)});`,
  '',
];

// ── carry the existing articles across ──────────────────────────────
const site = await import(pathToFileURL(path.join(ROOT, 'src/lib/site.ts')).href);
lines.push('DELETE FROM articles;', '');
for (const a of site.ARTICLES) {
  const id = crypto.randomUUID();
  lines.push(
    'INSERT INTO articles (id, slug, kind, status, title, standfirst, excerpt, reading_time, topic, featured, viz, viz_caption, service_name, service_slug, body_json, is_placeholder, created_at, updated_at, published_at) VALUES (' +
      [
        q(id), q(a.slug), q(a.kind), q('published'), q(a.title), q(a.standfirst),
        q(a.excerpt), q(a.readingTime), q(a.topic), a.featured ? 1 : 0, q(a.viz),
        q(a.vizCaption), q(a.service.name), q(a.service.slug),
        q(JSON.stringify(a.body)), 1, q(now), q(now), q(now),
      ].join(', ') + ');'
  );
}

fs.mkdirSync(path.join(ROOT, 'migrations'), { recursive: true });
const sqlPath = path.join(ROOT, 'migrations', '0003_seed.sql');
fs.writeFileSync(sqlPath, lines.join('\n') + '\n', 'utf8');

fs.mkdirSync(path.join(ROOT, 'data'), { recursive: true });
const pwPath = path.join(ROOT, 'data', 'ADMIN_PASSWORD.txt');
fs.writeFileSync(
  pwPath,
  [
    'LAHAV AI admin credentials',
    '',
    'email:    ' + ADMIN_EMAIL,
    'password: ' + password,
    '',
    generated
      ? 'This password was generated and is stored ONLY in this file.'
      : 'This password came from ADMIN_PASSWORD.',
    'Move it into a password manager and then delete this file.',
    'This file is gitignored and must never be committed or shared.',
    '',
  ].join('\n'),
  'utf8'
);

console.log('wrote ' + path.relative(ROOT, sqlPath));
console.log('wrote ' + path.relative(ROOT, pwPath) + '   <- the password is in here, not printed');
console.log('articles seeded: ' + site.ARTICLES.length);
console.log('admin email:     ' + ADMIN_EMAIL);
